### ISSUE TITLE
Get automatically hook prefix

### ISSUE THREAD

**Issue by mikaoelitiana** [favish/atom-drupal#12]
Hook prefix can be automatically set from current file name or folder name. So when i run snippet h.menu, it will automatically replace "hook" with the custom module name from filename.

**Comment by michaelfavia** [comment]
Great idea! If you'd like to submit a PR id be happy to include it. Please be sure it deals with non .module files too like views hooks, etc.

**Comment by robballou** [comment]
Is this supported now? I've tried in the past... :disappointed:

See:

* https://github.com/atom/snippets/issues/148
* https://github.com/atom/snippets/issues/46

If it is supported now I can help get this in there.

**Comment by mikaoelitiana** [comment]
I don't know if it is yet supported but I will check it.

**Comment by nvaken** [comment]
I'd like to add that PHP Storm's Drupal integration might be a good place to find some inspiration. The Drupal plugin there is truly magnificent. When you start typing your module name, it simply suggests hook function names.

**Comment by abdennour** [comment]
I will leave ATOM because this lack  And i switch to VIM because of [this feature](http://stackoverflow.com/q/12232379/747579).

### See you in VIM community.

**Comment by michaelfavia** [comment]
@abdennour: or you could be the change you wish to see in the world and write it! Best of luck.
