### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by nvaken** [favish/atom-drupal#15]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1143:5)
Object.activate (/Users/nvaken/.atom/dev/packages/drupal/lib/drupal.coffee:6:22)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26)
```

**Comment by robballou** [comment]
Which version of Atom does this affect?

**Comment by nvaken** [comment]
That would be `1.9.8`

**Comment by robballou** [comment]
I didn't get the warning myself, but I have applied a fix in the master branch if you want to test it out.

Thanks!

**Comment by nvaken** [comment]
I'm not sure when this was triggered, just saw it this one time. Since I'm unable to reproduce, I'll close it for now, fix seems legit to me.

**Comment by jeffgeorge** [comment]
@robballou I'm seeing this same warning in the Deprecation Cop in Atom 1.13.0-beta8. Can you please tag a new release with this fix included?

**Comment by robballou** [comment]
I don't think I can make new releases via APM, etc., but have tagged @michaelfavia who can.

**Comment by michaelfavia** [comment]
Release rolled and published. Testing it now. THanks @robballou and @jeffgeorge
