### ISSUE TITLE
Failed to load snippets from '/Users/[user]/.atom/packages/drupal/snippets/commerce.cson'

### ISSUE THREAD

**Issue by truls1502** [favish/atom-drupal#17]
I got a red error message which stated _`/Users/[user]/.atom/packages/drupal/snippets/commerce.cson: Duplicate key 'h.commerce_entity_create_alter()'`_ once I open the Atom program.

I am using the latest version of Atom: 1.26.1

**Comment by a-mawlawi** [comment]
I got the same error.

**Comment by aoristos** [comment]
I found a sequence of duplicate code in the file 'commerce.cson' (lines 70-76 are identical with lines 81-87)
The duplicate sequence can be deleted (or commented) to omit the error message.

seraching for duplicate sequence:
![commerce_entity_create search duplicated snippet](https://user-images.githubusercontent.com/39117873/39804426-46626180-5374-11e8-8ad3-9c7480a242bc.png)

commenting the duplicate sequence:
![commerce_entity_create duplicated snippet](https://user-images.githubusercontent.com/39117873/39804454-50af9e32-5374-11e8-953a-4e686ff6e7cc.png)
